apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  annotations:
    kubernetes.io/ingress.class: nginx  
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  namespace: heimdall
spec:
  tls:
    - hosts:
        - heimdall.127.0.0.1.nip.io
      secretName: tls-heimdall-ingress
