apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: heimdall
    namespace: heimdall
    version: v1
images:
- name: linuxserver/heimdall
  newName: linuxserver/heimdall
  newTag: 2.5.5
