apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  namespace: heimdall
spec:
  rules:
    - host: heimdall.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: heimdall
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: ''
