kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-pvc
  namespace: heimdall
  labels:
    app: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
